server.port=8080

spring.application.name=ai-code-review-agent

management.endpoints.web.exposure.include=health,info

springdoc.swagger-ui.path=/swagger-ui.html

agent.dry-run=false
agent.create-jira-ticket=true
agent.post-github-comment=true

github.token=${GH_PAT}
github.api-url=https://api.github.com

jira.base-url=${JIRA_BASE_URL}
jira.email=${JIRA_EMAIL}
jira.api-token=${JIRA_API_TOKEN}
jira.project-key=${JIRA_PROJECT_KEY}
jira.issue-type=Task