server.port=8080

spring.application.name=ai-code-review-agent

management.endpoints.web.exposure.include=health,info

springdoc.swagger-ui.path=/swagger-ui.html

agent.dry-run=true
agent.create-jira-ticket=true
agent.post-github-comment=true

github.token=${GITHUB_TOKEN:dummy-token}
github.api-url=https://api.github.com

jira.base-url=https://mayanknittrr.atlassian.net
jira.email=tarunjeetsingh.91@gmail.com
jira.api-token=ATATT3xFfGF0RwcSOx0MI3CNcXof4dmD7YKCPlx8LOQoiuW22xTmmWc0d2YIIhFK9531KJj0S_m97ygFGPoB4yr8UL0GEZDJqERlWOKxXvM9sXg5QwgDbay3d5dyjeUFc2BW1QvS8AovetXYTXpUU4e6pbvTLSSAav_hpkBXmG_8-yOP5HDqsxI=8039FF24
jira.project-key=SCRUM
jira.issue-type=Task